<aside class="admin-sidebar">
  <nav class="sidebar-nav">
    <x-admin.sidebar-section >
      <li>
        <x-admin.sidebar-nav-link 
          :route="route('admin.dashboard')"
          :active="request()->routeIs('admin.dashboard')" 
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Dashboard
        </x-admin.sidebar-nav-link>
      </li>
    </x-admin.sidebar-section>
    
    <x-admin.sidebar-section title="Componentes">
      <li>
        <x-admin.sidebar-nav-link 
          :route="route('admin.factions.index')"
          :active="request()->routeIs('admin.factions.*')" 
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Facciones
        </x-admin.sidebar-nav-link>
      </li>
      <li>
        <x-admin.sidebar-nav-link 
          :route="route('admin.hero-abilities.index')"
          :active="request()->routeIs('admin.hero-abilities.*')" 
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Habilidades
        </x-admin.sidebar-nav-link>
      </li>
      <li>
        <x-admin.sidebar-nav-link 
          route="#"
          :active="request()->routeIs('admin.heroes.*')" 
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Héroes
        </x-admin.sidebar-nav-link>
      </li>
    </x-admin.sidebar-section>

    <x-admin.sidebar-section title="Balance">
      <li>
        <x-admin.sidebar-nav-link 
          :route="route('admin.hero-attributes.edit')"
          :active="request()->routeIs('admin.hero-attributes.*')" 
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Configuración de Atributos
        </x-admin.sidebar-nav-link>
      </li>
      <li>
        <x-admin.sidebar-nav-link 
          :route="route('admin.hero-superclasses.index')"
          :active="request()->routeIs('admin.hero-superclasses.*')" 
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Superclases
        </x-admin.sidebar-nav-link>
      </li>
      <li>
        <x-admin.sidebar-nav-link 
          :route="route('admin.hero-classes.index')"
          :active="request()->routeIs('admin.hero-classes.*')"  
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Clases
        </x-admin.sidebar-nav-link>
      </li>
    </x-admin.sidebar-section>

    <x-admin.sidebar-section title="Habilidades">
      <li>
        <x-admin.sidebar-nav-link 
          :route="route('admin.attack-types.index')"
          :active="request()->routeIs('admin.attack-types.*')" 
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Tipos
        </x-admin.sidebar-nav-link>
      </li>
      <li>
        <x-admin.sidebar-nav-link 
          :route="route('admin.attack-subtypes.index')"
          :active="request()->routeIs('admin.attack-subtypes.*')" 
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Subtipos
        </x-admin.sidebar-nav-link>
      </li>
      <li>
        <x-admin.sidebar-nav-link 
          :route="route('admin.attack-ranges.index')"
          :active="request()->routeIs('admin.attack-ranges.*')" 
          icon="solid"
          color1="#FFD976"
          color2="#FFD976"
          color3="#FFD976"
        >
          Rangos
        </x-admin.sidebar-nav-link>
      </li>
    </x-admin.sidebar-section>
  </nav>
</aside>